# Generated by Django 5.1.1 on 2024-11-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comites_api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglamento',
            name='gravedad',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('verificacionquorom', models.CharField(max_length=600)),
                ('verificacionasistenciaaprendiz', models.CharField(max_length=600)),
                ('verificacionbeneficio', models.CharField(max_length=600)),
                ('reporte', models.CharField(max_length=600)),
                ('descargos', models.CharField(max_length=600)),
                ('pruebas', models.CharField(max_length=600)),
                ('deliberacion', models.CharField(max_length=600)),
                ('votos', models.CharField(max_length=600)),
                ('conclusiones', models.CharField(max_length=600)),
                ('lasificacioninformacion', models.CharField(blank=True, choices=[('PUBLICA', 'PUBLICA'), ('PRIVADO', 'PRIVADO'), ('SEMIPRIVADO', 'SEMIPRIVADO'), ('SENSISBLE', 'SENSISBLE')], default='PUBLICA', max_length=15, null=True)),
                ('citacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comites_api.citacion')),
            ],
        ),
    ]
